apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  DB_USER: ZWNvbW1lcmNlX3VzZXI= # base64 for "ecommerce_user"
  DB_PASSWORD: cGFzc3dvcmQxMjM= # base64 for "password123"
  JWT_SECRET: c2VjcmV0a2V5MTIz # Base64 for "secretkey123"
