apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nextjs
  template:
    metadata:
      labels:
        app: nextjs
    spec:
      containers:
      - name: nextjs
        image: yazilansari/nextjs-app:d2923b5eed8d54ea295f3c9377189b686aaae182
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: NEXT_PUBLIC_PRODUCTS_API_URL
          value: "http://api.172-18-0-3.nip.io/products"
        - name: NEXT_PUBLIC_ORDERS_API_URL
          value: "http://api.172-18-0-3.nip.io/orders"
        - name: NEXT_PUBLIC_PAYMENT_API_URL
          value: "http://api.172-18-0-3.nip.io/payment"
        - name: NEXT_PUBLIC_AUTH_API_URL
          value: "http://api.172-18-0-3.nip.io/auth/signin"
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
