apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events {}
    http {
      server {
        listen 80;
        server_name next.local;

        location / {
          proxy_pass http://nextjs-service:3000;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
        }
      }

      server {
        listen 80;
        server_name api.next.local;

        location /products {
          proxy_pass http://products-service:3000/products;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;

           # CORS Headers
          add_header 'Access-Control-Allow-Origin' 'http://next.local:8080' always;
          add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS' always;
          add_header 'Access-Control-Allow-Headers' 'Content-Type, Authorization' always;
          add_header 'Access-Control-Allow-Credentials' 'true' always;

          # Handle OPTIONS preflight requests
          if ($request_method = 'OPTIONS') {
           add_header 'Access-Control-Allow-Origin' 'http://next.local:8080';
           add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
           add_header 'Access-Control-Allow-Headers' 'Content-Type, Authorization';
           add_header 'Access-Control-Allow-Credentials' 'true';
           return 204;
          }
        }

        location /orders {
          proxy_pass http://orders-service:3000/orders;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;

           # CORS Headers
          add_header 'Access-Control-Allow-Origin' 'http://next.local:8080' always;
          add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS' always;
          add_header 'Access-Control-Allow-Headers' 'Content-Type, Authorization' always;
          add_header 'Access-Control-Allow-Credentials' 'true' always;

          # Handle OPTIONS preflight requests
          if ($request_method = 'OPTIONS') {
           add_header 'Access-Control-Allow-Origin' 'http://next.local:8080';
           add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
           add_header 'Access-Control-Allow-Headers' 'Content-Type, Authorization';
           add_header 'Access-Control-Allow-Credentials' 'true';
           return 204;
          }
        }

        location /payment {
          proxy_pass http://payment-service:3000/payment;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;

           # CORS Headers
          add_header 'Access-Control-Allow-Origin' 'http://next.local:8080' always;
          add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS' always;
          add_header 'Access-Control-Allow-Headers' 'Content-Type, Authorization' always;
          add_header 'Access-Control-Allow-Credentials' 'true' always;

          # Handle OPTIONS preflight requests
          if ($request_method = 'OPTIONS') {
           add_header 'Access-Control-Allow-Origin' 'http://next.local:8080';
           add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
           add_header 'Access-Control-Allow-Headers' 'Content-Type, Authorization';
           add_header 'Access-Control-Allow-Credentials' 'true';
           return 204;
          }
        }

        location /auth {
          proxy_pass http://auth-service:3000/auth;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;

           # CORS Headers
          add_header 'Access-Control-Allow-Origin' 'http://next.local:8080' always;
          add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS' always;
          add_header 'Access-Control-Allow-Headers' 'Content-Type, Authorization' always;
          add_header 'Access-Control-Allow-Credentials' 'true' always;

          # Handle OPTIONS preflight requests
          if ($request_method = 'OPTIONS') {
           add_header 'Access-Control-Allow-Origin' 'http://next.local:8080';
           add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
           add_header 'Access-Control-Allow-Headers' 'Content-Type, Authorization';
           add_header 'Access-Control-Allow-Credentials' 'true';
           return 204;
          }
        }
      }
    }
