apiVersion: v1
kind: Service
metadata:
  name: orders-service
  namespace: ecommerce
spec:
  selector:
    app: orders
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
  type: ClusterIP
