name: Build Service

on:
  workflow_call:
    inputs:
      service:
        required: true
        type: string
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'  # Enable npm cache for the global npm cache directory
          cache-dependency-path: ${{ inputs.service }}/package-lock.json

      - name: Cache node_modules
        uses: actions/cache@v4
        id: cache-node-modules
        with:
          path: ${{ inputs.service }}/node_modules
          key: ${{ runner.os }}-node-modules-${{ inputs.service }}-${{ hashFiles('${{ inputs.service }}/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-${{ inputs.service }}-

      - name: Install dependencies & run tests
        run: |
          cd ${{ inputs.service }}
          npm install
          npm test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./${{ inputs.service }}
          push: false
          tags: yazilansari/${{ inputs.service }}:${{ github.sha }}
          outputs: type=docker,dest=/tmp/${{ inputs.service }}.tar

      - name: Load Docker image
        run: docker load -i /tmp/${{ inputs.service }}.tar || echo "Failed to load image"

      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: yazilansari/${{ inputs.service }}:${{ github.sha }}
          format: table
          exit-code: 0
          severity: CRITICAL,HIGH
          ignore-unfixed: true

      - name: Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./${{ inputs.service }}
          push: true
          tags: yazilansari/${{ inputs.service }}:${{ github.sha }}