name: CI/CD Pipeline
on:
  push:
    branches: [master]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install dependencies for nextjs-app
      run: |
        cd nextjs-app
        npm install

    - name: Install dependencies for auth-service
      run: |
        cd auth-service
        npm install

    - name: Install dependencies for orders-service
      run: |
        cd orders-service
        npm install

    - name: Install dependencies for payment-service
      run: |
        cd payment-service
        npm install

    - name: Install dependencies for products-service
      run: |
        cd products-service
        npm install

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push nextjs-app
      uses: docker/build-push-action@v5
      with:
        context: ./nextjs-app
        push: true
        tags: |
          yazilansari/nextjs-app:latest
          yazilansari/nextjs-app:${{ github.sha }}

    - name: Build and push auth-service
      uses: docker/build-push-action@v5
      with:
        context: ./auth-service
        push: true
        tags: |
          yazilansari/auth-service:latest
          yazilansari/auth-service:${{ github.sha }}

    - name: Build and push orders-service
      uses: docker/build-push-action@v5
      with:
        context: ./orders-service
        push: true
        tags: |
          yazilansari/orders-service:latest
          yazilansari/orders-service:${{ github.sha }}

    - name: Build and push payment-service
      uses: docker/build-push-action@v5
      with:
        context: ./payment-service
        push: true
        tags: |
          yazilansari/payment-service:latest
          yazilansari/payment-service:${{ github.sha }}

    - name: Build and push products-service
      uses: docker/build-push-action@v5
      with:
        context: ./products-service
        push: true
        tags: |
          yazilansari/products-servicelatest
          yazilansari/products-service:${{ github.sha }}

    - name: Set up Minikube
      uses: medyagh/setup-minikube@v0.0.16
      with:
        minikube-version: 'latest'
        driver: docker

    - name: Deploy to Minikube
      run: |
        minikube start
        kubectl apply -f k8s/
        kubectl rollout status deployment/nextjs-deployment
        kubectl rollout status deployment/auth-deployment
        kubectl rollout status deployment/orders-deployment
        kubectl rollout status deployment/payment-deployment
        kubectl rollout status deployment/products-deployment
