name: CI Pipeline
on:
  push:
    branches: [dev]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: dev

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install dependencies for nextjs-app
      run: |
        cd nextjs-app
        npm install
        npm test

    - name: Install dependencies for auth-service
      run: |
        cd auth-service
        npm install
        npm test

    - name: Install dependencies for orders-service
      run: |
        cd orders-service
        npm install
        npm test

    - name: Install dependencies for payment-service
      run: |
        cd payment-service
        npm install
        npm test

    - name: Install dependencies for products-service
      run: |
        cd products-service
        npm install
        npm test

    - name: Debug SonarQube connectivity
      run: |
        curl -v ${{ secrets.SONAR_URL }}/api/server/version || echo "Failed to reach SonarQube"
        curl -u ${{ secrets.SONAR_TOKEN}}: ${{ secrets.SONAR_URL }}/api/projects/search || echo "Token auth failed"
        # ping -c 4 https://1403-86-98-147-96.ngrok-free.app || echo "Ping failed"

    - name: SonarQube Scan with Retry
      uses: nick-fields/retry@v3
      with:
        timeout_seconds: 600
        max_attempts: 3
        command: |
          docker run --rm -e SONAR_HOST_URL=${{ secrets.SONAR_URL }} -e SONAR_TOKEN=${{ secrets.SONAR_TOKEN }} \
          -v $(pwd):/usr/src sonarsource/sonar-scanner-cli:latest \
          -Dsonar.projectBaseDir=. -Dsonar.qualitygate.wait=true -Dsonar.qualitygate.timeout=300 -Dsonar.verbose=true \
          -Dsonar.scanner.force-deprecated-java-version-check=false

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build nextjs-app
      uses: docker/build-push-action@v5
      with:
        context: ./nextjs-app
        push: false
        tags: yazilansari/nextjs-app:${{ github.sha }}
        outputs: type=docker,dest=/tmp/nextjs-app.tar

    - name: Debug nextjs-app build
      run: |
        ls -lh /tmp/nextjs-app.tar || echo "nextjs-app.tar not found"
        docker images | grep yazilansari/nextjs-app || echo "No nextjs-app image found"
        docker load -i /tmp/nextjs-app.tar || echo "Failed to load nextjs-app.tar"

    # - name: Debug Trivy environment
    #   run: |
    #     pwd
    #     ls -lh nextjs-app/.trivyignore || echo "nextjs-app/.trivyignore not found"
    #     cat nextjs-app/.trivyignore || echo "Failed to read nextjs-app/.trivyignore"
    #     file nextjs-app/.trivyignore || echo "Failed to inspect nextjs-app/.trivyignore"

    - name: Scan nextjs-app image with Trivy
      uses: aquasecurity/trivy-action@0.24.0
      with:
        image-ref: yazilansari/nextjs-app:${{ github.sha }}
        format: table
        exit-code: 0
        severity: CRITICAL,HIGH
        ignore-unfixed: true
    #     trivy-flags: --ignore CVE-2024-21538,CVE-2025-29927

    - name: Push nextjs-app
      uses: docker/build-push-action@v5
      with:
        context: ./nextjs-app
        push: true
        tags: yazilansari/nextjs-app:${{ github.sha }}

    - name: Build auth-service
      uses: docker/build-push-action@v5
      with:
        context: ./auth-service
        push: false
        tags: yazilansari/auth-service:${{ github.sha }}
        outputs: type=docker,dest=/tmp/auth-service.tar

    - name: Debug auth-service build
      run: |
        ls -lh /tmp/auth-service.tar || echo "auth-service.tar not found"
        docker images | grep yazilansari/auth-service || echo "No auth-service image found"
        docker load -i /tmp/auth-service.tar || echo "Failed to load auth-service.tar"

    # - name: Debug Trivy environment
    #   run: |
    #     pwd
    #     ls -lh auth-service/.trivyignore || echo "auth-service/.trivyignore not found"
    #     cat auth-service/.trivyignore || echo "Failed to read auth-service/.trivyignore"
    #     file auth-service/.trivyignore || echo "Failed to inspect auth-service/.trivyignore"

    - name: Scan auth-service image with Trivy
      uses: aquasecurity/trivy-action@0.24.0s
      with:
        image-ref: yazilansari/auth-service:${{ github.sha }}
        format: table
        exit-code: 0
        severity: CRITICAL,HIGH
        ignore-unfixed: true

    - name: Push auth-service
      uses: docker/build-push-action@v5
      with:
        context: ./auth-service
        push: true
        tags: yazilansari/auth-service:${{ github.sha }}

    - name: Build orders-service
      uses: docker/build-push-action@v5
      with:
        context: ./orders-service
        push: false
        tags: yazilansari/orders-service:${{ github.sha }}
        outputs: type=docker,dest=/tmp/orders-service.tar

    - name: Debug orders-service build
      run: |
        ls -lh /tmp/orders-service.tar || echo "orders-service.tar not found"
        docker images | grep yazilansari/orders-service || echo "No orders-service image found"
        docker load -i /tmp/orders-service.tar || echo "Failed to load orders-service.tar"

    # - name: Debug Trivy environment
    #   run: |
    #     pwd
    #     ls -lh orders-service/.trivyignore || echo "orders-service/.trivyignore not found"
    #     cat orders-service/.trivyignore || echo "Failed to read orders-service/.trivyignore"
    #     file orders-service/.trivyignore || echo "Failed to inspect orders-service/.trivyignore"

    - name: Scan orders-service image with Trivy
      uses: aquasecurity/trivy-action@0.24.0
      with:
        image-ref: yazilansari/orders-service:${{ github.sha }}
        format: table
        exit-code: 0
        severity: CRITICAL,HIGH
        ignore-unfixed: true

    - name: Push orders-service
      uses: docker/build-push-action@v5
      with:
        context: ./orders-service
        push: true
        tags: yazilansari/orders-service:${{ github.sha }}

    - name: Build payment-service
      uses: docker/build-push-action@v5
      with:
        context: ./payment-service
        push: false
        tags: yazilansari/payment-service:${{ github.sha }}
        outputs: type=docker,dest=/tmp/payment-service.tar

    - name: Debug payment-service build
      run: |
        ls -lh /tmp/payment-service.tar || echo "payment-service.tar not found"
        docker images | grep yazilansari/payment-service || echo "No payment-service image found"
        docker load -i /tmp/payment-service.tar || echo "Failed to load payment-service.tar"

    # - name: Debug Trivy environment
    #   run: |
    #     pwd
    #     ls -lh payment-service/.trivyignore || echo "payment-service/.trivyignore not found"
    #     cat payment-service/.trivyignore || echo "Failed to read payment-service/.trivyignore"
    #     file payment-service/.trivyignore || echo "Failed to inspect payment-service/.trivyignore"

    - name: Scan payment-service image with Trivy
      uses: aquasecurity/trivy-action@0.24.0
      with:
        image-ref: yazilansari/payment-service:${{ github.sha }}
        format: table
        exit-code: 0
        severity: CRITICAL,HIGH
        ignore-unfixed: true

    - name: Push payment-service
      uses: docker/build-push-action@v5
      with:
        context: ./payment-service
        push: true
        tags: yazilansari/payment-service:${{ github.sha }}      

    - name: Build products-service
      uses: docker/build-push-action@v5
      with:
        context: ./products-service
        push: false
        tags: yazilansari/products-service:${{ github.sha }}
        outputs: type=docker,dest=/tmp/products-service.tar

    - name: Debug products-service build
      run: |
        ls -lh /tmp/products-service.tar || echo "products-service.tar not found"
        docker images | grep yazilansari/products-service || echo "No products-service image found"
        docker load -i /tmp/products-service.tar || echo "Failed to load products-service.tar"

    # - name: Debug Trivy environment
    #   run: |
    #     pwd
    #     ls -lh products-service/.trivyignore || echo "products-service/.trivyignore not found"
    #     cat products-service/.trivyignore || echo "Failed to read products-service/.trivyignore"
    #     file products-service/.trivyignore || echo "Failed to inspect products-service/.trivyignore"

    - name: Scan products-service image with Trivy
      uses: aquasecurity/trivy-action@0.24.0
      with:
        image-ref: yazilansari/products-service:${{ github.sha }}
        format: table
        exit-code: 0
        severity: CRITICAL,HIGH
        ignore-unfixed: true

    - name: Push products-service
      uses: docker/build-push-action@v5
      with:
        context: ./products-service
        push: true
        tags: yazilansari/products-service:${{ github.sha }}

    - name: Update deployment image tags
      run: |
        sed -i "s|yazilansari/nextjs-app:.*|yazilansari/nextjs-app:${{ github.sha }}|" k8s/nextjs-deployment.yaml
        sed -i "s|yazilansari/auth-service:.*|yazilansari/auth-service:${{ github.sha }}|" k8s/auth-deployment.yaml
        sed -i "s|yazilansari/orders-service:.*|yazilansari/orders-service:${{ github.sha }}|" k8s/orders-deployment.yaml
        sed -i "s|yazilansari/payment-service:.*|yazilansari/payment-service:${{ github.sha }}|" k8s/payment-deployment.yaml
        sed -i "s|yazilansari/products-service:.*|yazilansari/products-service:${{ github.sha }}|" k8s/products-deployment.yaml
        cat k8s/nextjs-deployment.yaml
        cat k8s/auth-deployment.yaml
        cat k8s/orders-deployment.yaml
        cat k8s/payment-deployment.yaml
        cat k8s/products-deployment.yaml

    - name: Commit and push updated manifests
      run: |
        git config --global user.name 'Yazil Ansari'
        git config --global user.email 'yazilansari03@gmail.com'
        git add k8s/*.yaml
        git commit -m "Update deployment image tags to ${{ github.sha }}"
        #git remote set-url origin https://x-access-token:${{ secrets.PAT }}@github.com/yazilansari/ecommerce-dev-ops.git
        git push
