name: CI Pipeline
on:
  push:
    branches: [dev]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: dev

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install dependencies for nextjs-app
      run: |
        cd nextjs-app
        npm install
        npm test

    - name: Install dependencies for auth-service
      run: |
        cd auth-service
        npm install
        npm test

    - name: Install dependencies for orders-service
      run: |
        cd orders-service
        npm install
        npm test

    - name: Install dependencies for payment-service
      run: |
        cd payment-service
        npm install
        npm test

    - name: Install dependencies for products-service
      run: |
        cd products-service
        npm install
        npm test

    - name: Debug SonarQube connectivity
      run: |
        curl -v http://192.168.28.128:9000/api/server/version || echo "Failed to reach SonarQube"
        curl -u ${{ secrets.SONAR_TOKEN}}: http://192.168.28.128:9000/api/projects/search || echo "Token auth failed"
        ping -c 4 192.168.28.128 || echo "Ping failed"

    - name: SonarQube Scan with Retry
      uses: nick-fields/retry@v3
      with:
        timeout_seconds: 600
        max_attempts: 3
        command: |
          docker run --rm -e SONAR_HOST_URL=http://192.168.28.128:9000 -e SONAR_TOKEN=${{ secrets.SONAR_TOKEN }} \
          -v $(pwd):/usr/src sonarsource/sonar-scanner-cli:latest \
          -Dsonar.projectBaseDir=. -Dsonar.qualitygate.wait=true -Dsonar.qualitygate.timeout=300 -Dsonar.verbose=true \
          -Dsonar.scanner.force-deprecated-java-version-check=false

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build nextjs-app
      uses: docker/build-push-action@v5
      with:
        context: ./nextjs-app
        push: false
        tags: yazilansari/nextjs-app:${{ github.sha }}
        outputs: type=docker,dest=/tmp/nextjs-app.tar

    - name: Scan nextjs-app image with Trivy
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: /tmp/nextjs-app.tar
        format: table
        exit-code: 1
        severity: CRITICAL,HIGH
        ignore-unfixed: true

    - name: Push nextjs-app
      uses: docker/build-push-action@v5
      with:
        context: ./nextjs-app
        push: true
        tags: yazilansari/nextjs-app:${{ github.sha }}

    - name: Build auth-service
      uses: docker/build-push-action@v5
      with:
        context: ./auth-service
        push: false
        tags: yazilansari/auth-service:${{ github.sha }}
        outputs: type=docker,dest=/tmp/auth-service.tar

    - name: Scan auth-service image with Trivy
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: /tmp/auth-service.tar
        format: table
        exit-code: 1
        severity: CRITICAL,HIGH
        ignore-unfixed: true

    - name: Push auth-service
      uses: docker/build-push-action@v5
      with:
        context: ./auth-service
        push: true
        tags: yazilansari/auth-service:${{ github.sha }}

    - name: Build orders-service
      uses: docker/build-push-action@v5
      with:
        context: ./orders-service
        push: false
        tags: yazilansari/orders-service:${{ github.sha }}
        outputs: type=docker,dest=/tmp/orders-service.tar

    - name: Scan orders-service image with Trivy
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: /tmp/orders-service.tar
        format: table
        exit-code: 1
        severity: CRITICAL,HIGH
        ignore-unfixed: true

    - name: Push orders-service
      uses: docker/build-push-action@v5
      with:
        context: ./orders-service
        push: true
        tags: yazilansari/orders-service:${{ github.sha }}

    - name: Build payment-service
      uses: docker/build-push-action@v5
      with:
        context: ./payment-service
        push: false
        tags: yazilansari/payment-service:${{ github.sha }}
        outputs: type=docker,dest=/tmp/payment-service.tar

    - name: Scan payment-service image with Trivy
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: /tmp/payment-service.tar
        format: table
        exit-code: 1
        severity: CRITICAL,HIGH
        ignore-unfixed: true

    - name: Push payment-service
      uses: docker/build-push-action@v5
      with:
        context: ./payment-service
        push: true
        tags: yazilansari/payment-service:${{ github.sha }}      

    - name: Build products-service
      uses: docker/build-push-action@v5
      with:
        context: ./products-service
        push: false
        tags: yazilansari/products-service:${{ github.sha }}
        outputs: type=docker,dest=/tmp/products-service.tar

    - name: Scan products-service image with Trivy
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: /tmp/products-service.tar
        format: table
        exit-code: 1
        severity: CRITICAL,HIGH
        ignore-unfixed: true

    - name: Push products-service
      uses: docker/build-push-action@v5
      with:
        context: ./products-service
        push: true
        tags: yazilansari/products-service:${{ github.sha }}

    - name: Update deployment image tags
      run: |
        sed -i "s|yazilansari/nextjs-app:.*|yazilansari/nextjs-app:${{ github.sha }}|" k8s/nextjs-deployment.yaml
        sed -i "s|yazilansari/auth-service:.*|yazilansari/auth-service:${{ github.sha }}|" k8s/auth-deployment.yaml
        sed -i "s|yazilansari/orders-service:.*|yazilansari/orders-service:${{ github.sha }}|" k8s/orders-deployment.yaml
        sed -i "s|yazilansari/payment-service:.*|yazilansari/payment-service:${{ github.sha }}|" k8s/payment-deployment.yaml
        sed -i "s|yazilansari/products-service:.*|yazilansari/products-service:${{ github.sha }}|" k8s/products-deployment.yaml
        cat k8s/nextjs-deployment.yaml
        cat k8s/auth-deployment.yaml
        cat k8s/orders-deployment.yaml
        cat k8s/payment-deployment.yaml
        cat k8s/products-deployment.yaml

    - name: Commit and push updated manifests
      run: |
        git config --global user.name 'Yazil Ansari'
        git config --global user.email 'yazilansari03@gmail.com'
        git add k8s/*.yaml
        git commit -m "Update deployment image tags to ${{ github.sha }}"
        #git remote set-url origin https://x-access-token:${{ secrets.PAT }}@github.com/yazilansari/ecommerce-dev-ops.git
        git push
